stages:
  - deploy

deploy-job:
  stage: deploy
  script:
    - if [ "$CI_COMMIT_TAG" = "" ] ; then echo "Need add tag!";
      else 
        ssh -o StrictHostKeyChecking=no ubuntu@app.venbergv.fun sudo chown ubuntu /var/www/venbergv.fun -R;
        scp -q -o StrictHostKeyChecking=no -r $CI_PROJECT_DIR/wp/* ubuntu@app.venbergv.fun:/var/www/venbergv.fun/;
        ssh -o StrictHostKeyChecking=no ubuntu@app.venbergv.fun sudo chown www-data /var/www/venbergv.fun -R;
      fi
    - echo "The End"
